name: Run Test
on:
  push:
    branches:
      - main 
  workflow_dispatch:
jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: exit 1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: | 
          npm ci
          npm run lint
          npx vitest run
          npm run build